const filters = document.querySelectorAll('.filter');
const cards = document.querySelectorAll('.final-card');
const finalPhotos = { 1975: '1975.webp', 1979: '1979.jpeg', 1983: '1983.jpeg', 1987: '1987.jpg', 1992: '1992.webp', 1996: '1996.jpg', 1999: '1999.webp', 2003: '2003.jpg', 2007: '2007.webp', 2011: '2011.avif', 2015: '2015.webp', 2019: '2019.jpg', 2023: '2023.avif' };
const hosts = { 1975: 'England', 1979: 'England', 1983: 'England & Wales', 1987: 'India & Pakistan', 1992: 'Australia & New Zealand', 1996: 'India, Pakistan & Sri Lanka', 1999: 'England, Wales, Scotland, Ireland & the Netherlands', 2003: 'South Africa, Zimbabwe & Kenya', 2007: 'West Indies', 2011: 'India, Sri Lanka & Bangladesh', 2015: 'Australia & New Zealand', 2019: 'England & Wales', 2023: 'India' };

const worldCups = {
  1975: { dates: '7–21 June 1975', participants: ['Australia', 'East Africa', 'England', 'India', 'New Zealand', 'Pakistan', 'Sri Lanka', 'West Indies'], champion: 'West Indies', runnerUp: 'Australia', semiFinalists: 'England, New Zealand', batter: 'Glenn Turner (New Zealand)', runs: '333 runs', bowler: 'Gary Gilmour (Australia)', wickets: '11 wickets', player: 'No official award', venues: ['Lord’s, London', 'The Oval, London', 'Edgbaston, Birmingham', 'Headingley, Leeds', 'Old Trafford, Manchester', 'Trent Bridge, Nottingham'], source: 'ICC historical overview and supplied final summary' },
  1979: { dates: '9–23 June 1979', participants: ['Australia', 'Canada', 'England', 'India', 'New Zealand', 'Pakistan', 'Sri Lanka', 'West Indies'], champion: 'West Indies', runnerUp: 'England', semiFinalists: 'New Zealand, Pakistan', batter: 'Gordon Greenidge (West Indies)', runs: '253 runs', bowler: 'Mike Hendrick (England)', wickets: '10 wickets', player: 'No official award', venues: ['Lord’s, London', 'The Oval, London', 'Edgbaston, Birmingham', 'Old Trafford, Manchester', 'Trent Bridge, Nottingham', 'Headingley, Leeds'], source: 'ICC historical overview and supplied final summary' },
  1983: { dates: '9–25 June 1983', participants: ['Australia', 'England', 'India', 'New Zealand', 'Pakistan', 'Sri Lanka', 'West Indies', 'Zimbabwe'], champion: 'India', runnerUp: 'West Indies', semiFinalists: 'England, Pakistan', batter: 'David Gower (England)', runs: '384 runs', bowler: 'Roger Binny (India)', wickets: '18 wickets', player: 'No official award', venues: ['Lord’s, London', 'Trent Bridge, Nottingham', 'Headingley, Leeds', 'The Oval, London', 'Edgbaston, Birmingham', 'County Ground, Derby', 'County Ground, Bristol', 'County Ground, Taunton', 'County Ground, Chelmsford', 'St Helen’s, Swansea', 'Grace Road, Leicester', 'Old Trafford, Manchester', 'County Ground, Southampton', 'New Road, Worcester', 'Nevill Ground, Tunbridge Wells'], source: 'ICC historical overview and supplied final summary' },
  1987: { dates: '8 October–8 November 1987', participants: ['Australia', 'England', 'India', 'New Zealand', 'Pakistan', 'Sri Lanka', 'West Indies', 'Zimbabwe'], champion: 'Australia', runnerUp: 'England', semiFinalists: 'India, Pakistan', batter: 'Graham Gooch (England)', runs: '471 runs', bowler: 'Craig McDermott (Australia)', wickets: '18 wickets', player: 'No official award', venues: ['Eden Gardens, Kolkata', 'Wankhede Stadium, Mumbai', 'M. A. Chidambaram Stadium, Chennai', 'Lal Bahadur Shastri Stadium, Hyderabad', 'M. Chinnaswamy Stadium, Bengaluru', 'Nehru Stadium, Indore', 'Arun Jaitley Ground, Delhi', 'Sardar Patel Stadium, Ahmedabad', 'Sector 16 Stadium, Chandigarh', 'Barabati Stadium, Cuttack', 'Vidarbha Ground, Nagpur', 'Green Park, Kanpur', 'Sawai Mansingh Stadium, Jaipur', 'Nehru Stadium, Pune', 'Iqbal Stadium, Faisalabad', 'Municipal Stadium, Gujranwala', 'Niaz Stadium, Hyderabad', 'National Stadium, Karachi', 'Gaddafi Stadium, Lahore', 'Arbab Niaz Stadium, Peshawar', 'Pindi Club Ground, Rawalpindi'], source: 'ICC historical overview and supplied final summary' },
  1992: { dates: '22 February–25 March 1992', participants: ['Australia', 'England', 'India', 'New Zealand', 'Pakistan', 'South Africa', 'Sri Lanka', 'West Indies', 'Zimbabwe'], champion: 'Pakistan', runnerUp: 'England', semiFinalists: 'New Zealand, South Africa', batter: 'Martin Crowe (New Zealand)', runs: '456 runs', bowler: 'Wasim Akram (Pakistan)', wickets: '18 wickets', player: 'Martin Crowe (New Zealand)', venues: ['Adelaide Oval', 'Lavington Sports Oval, Albury', 'Eastern Oval, Ballarat', 'Berri Oval', 'The Gabba, Brisbane', 'Manuka Oval, Canberra', 'Bellerive Oval, Hobart', 'Ray Mitchell Oval, Mackay', 'Melbourne Cricket Ground', 'WACA Ground, Perth', 'Sydney Cricket Ground', 'Eden Park, Auckland', 'Lancaster Park, Christchurch', 'Carisbrook, Dunedin', 'Seddon Park, Hamilton', 'McLean Park, Napier', 'Pukekura Park, New Plymouth', 'Basin Reserve, Wellington'], source: 'ICC historical overview and supplied final summary' },
  1996: { dates: '14 February–17 March 1996', participants: ['Australia', 'England', 'India', 'Kenya', 'Netherlands', 'New Zealand', 'Pakistan', 'South Africa', 'Sri Lanka', 'United Arab Emirates', 'West Indies', 'Zimbabwe'], champion: 'Sri Lanka', runnerUp: 'Australia', semiFinalists: 'India, West Indies', batter: 'Sachin Tendulkar (India)', runs: '523 runs', bowler: 'Anil Kumble (India)', wickets: '15 wickets', player: 'Sanath Jayasuriya (Sri Lanka)', venues: ['India: 17 host grounds, including Eden Gardens, Wankhede, Feroz Shah Kotla, M. Chinnaswamy, M. A. Chidambaram, Green Park and PCA Stadium', 'Pakistan: National Stadium, Karachi', 'Pakistan: Gaddafi Stadium, Lahore', 'Pakistan: Rawalpindi Cricket Stadium', 'Pakistan: Arbab Niaz Stadium, Peshawar', 'Pakistan: Iqbal Stadium, Faisalabad', 'Pakistan: Jinnah Stadium, Gujranwala', 'Sri Lanka: R. Premadasa Stadium, Colombo', 'Sri Lanka: Sinhalese Sports Club, Colombo', 'Sri Lanka: Asgiriya Stadium, Kandy'], source: 'Tournament venue records and supplied final summary' },
  1999: { dates: '14 May–20 June 1999', participants: ['Australia', 'Bangladesh', 'England', 'India', 'Kenya', 'New Zealand', 'Pakistan', 'Scotland', 'South Africa', 'Sri Lanka', 'West Indies', 'Zimbabwe'], champion: 'Australia', runnerUp: 'Pakistan', semiFinalists: 'New Zealand, South Africa', batter: 'Rahul Dravid (India)', runs: '461 runs', bowler: 'Geoff Allott (New Zealand)', wickets: '20 wickets', player: 'Lance Klusener (South Africa)', venues: ['Edgbaston, Birmingham', 'County Ground, Bristol', 'St Lawrence Ground, Canterbury', 'County Ground, Chelmsford', 'Riverside Ground, Chester-le-Street', 'County Ground, Derby', 'County Ground, Hove', 'Headingley, Leeds', 'Grace Road, Leicester', 'Lord’s, London', 'The Oval, London', 'Old Trafford, Manchester', 'County Ground, Northampton', 'Trent Bridge, Nottingham', 'County Ground, Southampton', 'County Ground, Taunton', 'New Road, Worcester', 'Sophia Gardens, Cardiff', 'The Grange Club, Edinburgh', 'Clontarf, Dublin', 'VRA Ground, Amstelveen'], source: 'Tournament venue records and supplied final summary' },
  2003: { dates: '9 February–23 March 2003', participants: ['Australia', 'Bangladesh', 'Canada', 'England', 'India', 'Kenya', 'Namibia', 'Netherlands', 'New Zealand', 'Pakistan', 'South Africa', 'Sri Lanka', 'West Indies', 'Zimbabwe'], champion: 'Australia', runnerUp: 'India', semiFinalists: 'Kenya, Sri Lanka', batter: 'Sachin Tendulkar (India)', runs: '673 runs', bowler: 'Chaminda Vaas (Sri Lanka)', wickets: '23 wickets', player: 'Sachin Tendulkar (India)', venues: ['Wanderers, Johannesburg', 'Kingsmead, Durban', 'Newlands, Cape Town', 'Centurion Park', 'Goodyear Park, Bloemfontein', 'St George’s Park, Port Elizabeth', 'North West Cricket Stadium, Potchefstroom', 'Buffalo Park, East London', 'De Beers Diamond Oval, Kimberley', 'Boland Park, Paarl', 'Willowmoore Park, Benoni', 'Pietermaritzburg Oval', 'Harare Sports Club', 'Queens Sports Club, Bulawayo', 'Nairobi Gymkhana Club'], source: 'Tournament venue records and supplied final summary' },
  2007: { dates: '13 March–28 April 2007', participants: ['Australia', 'Bangladesh', 'Bermuda', 'Canada', 'England', 'India', 'Ireland', 'Kenya', 'Netherlands', 'New Zealand', 'Pakistan', 'Scotland', 'South Africa', 'Sri Lanka', 'West Indies', 'Zimbabwe'], champion: 'Australia', runnerUp: 'Sri Lanka', semiFinalists: 'New Zealand, South Africa', batter: 'Matthew Hayden (Australia)', runs: '659 runs', bowler: 'Glenn McGrath (Australia)', wickets: '26 wickets', player: 'Glenn McGrath (Australia)', venues: ['Kensington Oval, Barbados', 'Sabina Park, Jamaica', 'National Cricket Stadium, Grenada', 'Daren Sammy Stadium, Saint Lucia', 'Warner Park, Saint Kitts', 'Queen’s Park Oval, Trinidad', 'Sir Vivian Richards Stadium, Antigua', 'Providence Stadium, Guyana'], source: 'ICC historical overview and supplied final summary' },
  2011: { dates: '19 February–2 April 2011', participants: ['Australia', 'Bangladesh', 'Canada', 'England', 'India', 'Ireland', 'Kenya', 'Netherlands', 'New Zealand', 'Pakistan', 'South Africa', 'Sri Lanka', 'West Indies', 'Zimbabwe'], champion: 'India', runnerUp: 'Sri Lanka', semiFinalists: 'Pakistan, New Zealand', batter: 'Tillakaratne Dilshan (Sri Lanka)', runs: '500 runs', bowler: 'Shahid Afridi (Pakistan)', wickets: '21 wickets', player: 'Yuvraj Singh (India)', venues: ['Eden Gardens, Kolkata', 'M. A. Chidambaram Stadium, Chennai', 'Feroz Shah Kotla, Delhi', 'Vidarbha Stadium, Nagpur', 'Sardar Patel Stadium, Ahmedabad', 'Wankhede Stadium, Mumbai', 'PCA Stadium, Mohali', 'M. Chinnaswamy Stadium, Bengaluru', 'R. Premadasa Stadium, Colombo', 'Pallekele International Stadium, Kandy', 'Mahinda Rajapaksa Stadium, Sooriyawewa', 'Zahur Ahmed Chowdhury Stadium, Chittagong', 'Sher-e-Bangla Stadium, Dhaka'], source: 'ICC historical overview and supplied final summary' },
  2015: { dates: '14 February–29 March 2015', participants: ['Afghanistan', 'Australia', 'Bangladesh', 'England', 'India', 'Ireland', 'New Zealand', 'Pakistan', 'Scotland', 'South Africa', 'Sri Lanka', 'United Arab Emirates', 'West Indies', 'Zimbabwe'], champion: 'Australia', runnerUp: 'New Zealand', semiFinalists: 'India, South Africa', batter: 'Martin Guptill (New Zealand)', runs: '547 runs', bowler: 'Mitchell Starc (Australia)', wickets: '22 wickets', player: 'Mitchell Starc (Australia)', venues: ['Adelaide Oval', 'Bellerive Oval, Hobart', 'The Gabba, Brisbane', 'Manuka Oval, Canberra', 'Melbourne Cricket Ground', 'WACA Ground, Perth', 'Sydney Cricket Ground', 'Eden Park, Auckland', 'University Oval, Dunedin', 'Seddon Park, Hamilton', 'McLean Park, Napier', 'Saxton Oval, Nelson', 'Hagley Oval, Christchurch', 'Wellington Regional Stadium'], source: 'ICC historical overview and supplied final summary' },
  2019: { dates: '30 May–14 July 2019', participants: ['Afghanistan', 'Australia', 'Bangladesh', 'England', 'India', 'New Zealand', 'Pakistan', 'South Africa', 'Sri Lanka', 'West Indies'], champion: 'England', runnerUp: 'New Zealand', semiFinalists: 'Australia, India', batter: 'Rohit Sharma (India)', runs: '648 runs', bowler: 'Mitchell Starc (Australia)', wickets: '27 wickets', player: 'Kane Williamson (New Zealand)', venues: ['County Ground, Bristol', 'Sophia Gardens, Cardiff', 'Riverside Ground, Chester-le-Street', 'Edgbaston, Birmingham', 'Headingley, Leeds', 'Lord’s, London', 'Old Trafford, Manchester', 'The Oval, London', 'County Ground, Taunton', 'Trent Bridge, Nottingham', 'Hampshire Bowl, Southampton'], source: 'ICC historical overview and supplied final summary' },
  2023: { dates: '5 October–19 November 2023', participants: ['Afghanistan', 'Australia', 'Bangladesh', 'England', 'India', 'Netherlands', 'New Zealand', 'Pakistan', 'South Africa', 'Sri Lanka'], champion: 'Australia', runnerUp: 'India', semiFinalists: 'New Zealand, South Africa', batter: 'Virat Kohli (India)', runs: '765 runs', bowler: 'Mohammed Shami (India)', wickets: '24 wickets', player: 'Virat Kohli (India)', venues: ['Narendra Modi Stadium, Ahmedabad', 'M. Chinnaswamy Stadium, Bengaluru', 'M. A. Chidambaram Stadium, Chennai', 'Arun Jaitley Stadium, Delhi', 'HPCA Stadium, Dharamsala', 'Rajiv Gandhi Stadium, Hyderabad', 'Eden Gardens, Kolkata', 'BRSABV Ekana Stadium, Lucknow', 'Wankhede Stadium, Mumbai', 'MCA Stadium, Pune'], source: 'ICC Cricket World Cup 2023 venue guide and supplied final summary' }
};

const modal = document.createElement('div');
modal.className = 'modal-backdrop';
modal.innerHTML = '<section class="tournament-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-top"><div><p class="eyebrow">Tournament profile</p><h2 id="modal-title"></h2><p id="modal-subtitle"></p></div><button class="modal-close" aria-label="Close tournament details">×</button></div><div class="modal-body"><div class="detail-grid"><article class="detail-card"><h3>Final standings</h3><div class="standings" id="modal-standings"></div></article><article class="detail-card"><h3>Individual leaders</h3><div class="leader-grid" id="modal-leaders"></div></article><article class="detail-card venues-card"><h3>Host venues</h3><div class="venue-list" id="modal-venues"></div></article><article class="detail-card participants-card"><h3>Participating countries <small id="participant-count"></small></h3><div class="participant-list" id="modal-participants"></div></article></div><p class="modal-source" id="modal-source"></p></div></section>';
document.body.append(modal);

function openDetails(year) {
  const cup = worldCups[year];
  document.getElementById('modal-title').textContent = `${year} World Cup`;
  document.getElementById('modal-subtitle').textContent = `${cup.dates} · Hosted by ${hosts[year]}.`;
  document.getElementById('modal-standings').innerHTML = `<div class="standing"><span>Champions</span><strong>${cup.champion}</strong></div><div class="standing"><span>Runners-up</span><strong>${cup.runnerUp}</strong></div><div class="standing"><span>Semi-finalists</span><strong>${cup.semiFinalists}</strong></div><div class="standing"><span>Host country / region</span><strong>${hosts[year]}</strong></div>`;
  document.getElementById('modal-leaders').innerHTML = `<div class="leader"><span>Most runs</span><strong>${cup.batter}</strong><small>${cup.runs}</small></div><div class="leader"><span>Most wickets</span><strong>${cup.bowler}</strong><small>${cup.wickets}</small></div><div class="leader"><span>Player of tournament</span><strong>${cup.player}</strong><small>Official award where awarded</small></div>`;
  document.getElementById('modal-venues').innerHTML = cup.venues.map((venue) => `<span class="venue">${venue}</span>`).join('');
  document.getElementById('participant-count').textContent = `(${cup.participants.length})`;
  document.getElementById('modal-participants').innerHTML = cup.participants.map((country) => `<span class="participant">${country}</span>`).join('');
  document.getElementById('modal-source').textContent = `Data note: ${cup.source}.`;
  modal.classList.add('open');
  modal.querySelector('.modal-close').focus();
}

function closeDetails() { modal.classList.remove('open'); }

cards.forEach((card) => {
  const year = card.querySelector('.final-year').textContent.trim();
  const photo = document.createElement('img');
  photo.className = 'final-photo';
  photo.src = `assets/finals/${finalPhotos[year]}`;
  photo.alt = `${year} Cricket World Cup champions lifting the trophy`;
  photo.loading = 'lazy';
  card.firstElementChild.prepend(photo);
  const trigger = document.createElement('button');
  trigger.className = 'detail-trigger';
  trigger.textContent = 'Tournament details';
  trigger.addEventListener('click', () => openDetails(year));
  card.firstElementChild.append(trigger);
});

modal.addEventListener('click', (event) => { if (event.target === modal || event.target.closest('.modal-close')) closeDetails(); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeDetails(); });

filters.forEach((filter) => {
  filter.addEventListener('click', () => {
    const decade = filter.dataset.decade;
    filters.forEach((item) => item.classList.toggle('active', item === filter));
    cards.forEach((card) => card.classList.toggle('hidden', decade !== 'all' && card.dataset.decade !== decade));
  });
});

